"""Reports API Routes."""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from database.connection import get_db, Report, Prediction
import uuid
from datetime import datetime

router = APIRouter()


@router.get("/reports", summary="List all reports")
async def list_reports(db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Report).order_by(Report.created_at.desc()))
    return {"reports": result.scalars().all()}


@router.post("/reports/generate/{prediction_id}", summary="Generate a report for a prediction")
async def generate_report(prediction_id: str, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(Prediction).where(Prediction.prediction_id == prediction_id))
    pred = result.scalar_one_or_none()
    if not pred:
        raise HTTPException(status_code=404, detail="Prediction not found.")

    content = f"""
LUNG DISEASE DETECTION REPORT
==============================
Report ID     : {str(uuid.uuid4())[:8].upper()}
Generated     : {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
AI System     : Lung Disease Detector v1.0
Generated By  : AI (Academic System)

DIAGNOSIS
---------
Primary Condition : {pred.final_condition}
Confidence        : {pred.final_confidence:.1f}%
Urgency Level     : {pred.urgency_level.upper()}
Model Used        : {pred.selected_model}

MODEL COMPARISON
----------------
CNN    — Condition: {pred.cnn_primary_condition or 'N/A'}, Confidence: {pred.cnn_confidence or 'N/A'}%
ResNet — Condition: {pred.resnet_primary_condition or 'N/A'}, Confidence: {pred.resnet_confidence or 'N/A'}%
Selected: {pred.selected_model} (higher accuracy model)

PRECAUTIONS
-----------
{chr(10).join(f"• {p}" for p in (pred.precautions or []))}

DISCLAIMER
----------
This report is generated by an AI system for academic and clinical decision-support purposes only.
It does not constitute a medical diagnosis. All findings must be reviewed and verified
by a qualified radiologist or physician before any clinical decisions are made.
"""

    report = Report(
        report_id=str(uuid.uuid4())[:12],
        prediction_id=pred.id,
        report_content=content
    )
    db.add(report)
    await db.commit()
    return {"message": "Report generated.", "report_id": report.report_id, "content": content}
